services:
  app:
    container_name: ludusstudii
    image: golang:latest
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    ports:
      - "8080:8080"

  db:
    container_name: ludusstudiidb
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ludus
      POSTGRES_PASSWORD: ludus
      POSTGRES_DB: ludus_studii_user_db
    ports:
      - "5432:5432"
  
volumes:
  postgres-data: